version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/app/pb_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - backend
    environment:
      - TMDB=${TMDB}
      - EMAIL=${EMAIL}
      - PASSWD=${PASSWD}
      - PB_URL=http://backend:8090
      - ORIGIN=http://localhost:3333
